name: Run Tests

on:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
    secrets:
      OPENAI_API_KEY:
        required: true

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ inputs.git_ref }}
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.22"
      - name: Validate
        run: make validate
      - name: Install gptscript
        run: |
          curl https://get.gptscript.ai/releases/default_linux_amd64_v1/gptscript -o ./gptscriptexe
          chmod +x ./gptscriptexe
      - name: Run Tests
        env:
          GPTSCRIPT_BIN: ./gptscriptexe
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: make test

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ inputs.git_ref }}
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.22"
      - name: Install gptscript
        run: |
          curl https://get.gptscript.ai/releases/default_windows_amd64_v1/gptscript.exe -o gptscript.exe
      - name: Run Tests
        env:
          GPTSCRIPT_BIN: .\gptscript.exe
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GPTSCRIPT_CONFIG_FILE: .\config
        run: make test
